# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec451a3da14e0d63dbae0f230f673bd65405d9472d307739c7f1b713b30368bffc01f4f48e4d620495778d26067bcc9ceef6719730d643b05ad02a300acd0b2

test:
  secret_key_base: b596dd59e71294a82f8da3698d357bbbb7b2685d36d21f834a48bb29f98af6b21da6a5162220f120805c846c24f5ff651342b9f9cb4f4d09fd7d82241cd53524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
